In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('customer.csv')
df.sample(5)

age  gender   review education purchased
45   61    Male     Poor        PG       Yes
27   69  Female     Poor        PG        No
8    65  Female  Average        UG        No
48   39  Female     Good        UG       Yes
42   30  Female     Good        PG       Yes

In [3]:
df = df.iloc[:,2:]

In [4]:
df.head(5)

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [5]:
print(df['review'].unique())
print(df['education'].unique())
print(df['purchased'].unique())

['Average' 'Poor' 'Good']
['School' 'UG' 'PG']
['No' 'Yes']


## Train test split

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [7]:
X_train

review education
14     Poor        PG
34  Average    School
1      Poor        UG
21  Average        PG
46     Poor        PG
24  Average        PG
37  Average        PG
26     Poor        PG
31     Poor    School
6      Good    School
39     Poor        PG
13  Average    School
4   Average        UG
33     Good        PG
9      Good        UG
8   Average        UG
0   Average    School
12     Poor    School
49     Good        UG
11     Good        UG
35     Poor    School
38     Good    School
16     Poor        UG
40     Good    School
41     Good        PG
45     Poor        PG
2      Good        PG
25     Good    School
17     Poor        UG
44  Average        UG
5   Average    School
27     Poor        PG
29  Average        UG
36     Good        UG
15     Poor        UG
28     Poor    School
32  Average        UG
3      Good        PG
18     Good    School
23     Good    School

## Ordinal Encoder

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [13]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [14]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [15]:
X_train = oe.transform(X_train)
X_train

array([[0., 2.],
       [1., 0.],
       [0., 1.],
       [1., 2.],
       [0., 2.],
       [1., 2.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.]])

In [16]:
X_test = oe.transform(X_test)
X_test

array([[2., 1.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.]])

In [17]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoder

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()
le.fit(Y_train)

LabelEncoder()

In [20]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [21]:
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

In [22]:
Y_train

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0])

In [23]:
Y_test

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 1])