In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
X, y = load_diabetes(return_X_y = True)

In [3]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

In [5]:
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [6]:
print("M = ", reg.coef_)
print("C = ", reg.intercept_)

M =  [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
C =  151.88331005254167


In [7]:
y_pred = reg.predict(X_test)

print(r2_score(y_test, y_pred))

0.4399338661568969


In [52]:
class MiniBatchGD:
    def __init__(self, batch_size ,learning_rate = 0.01,epochs = 100):
        self.coef_ = None
        self.intercept_ = None
        self.batch_size = batch_size
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self, X_train, y_train):
        self.coef_ = np.ones(X_train.shape[1])
        self.intercept_ = 0

        for i in range(self.epochs):
            for j in range(int(X_train.shape[0] / self.batch_size)):
                idx = random.sample(range(X_train.shape[0]), self.batch_size)

                y_hat = self.intercept_ + np.dot(X_train[idx], self.coef_)
                

                intercept_derivative = -2 * np.mean(y_train[idx] - y_hat)
                
                self.intercept_ = self.intercept_ - (self.lr * intercept_derivative)

                coef_derivative = -2 * np.dot((y_train[idx] - y_hat), X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_derivative)

        print(self.coef_)
        print(self.intercept_)

    def predict(self, X_test):
        return np.dot(X_test, self.coef_) + self.intercept_

In [28]:
np.ones(X_train.shape[1])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
X_train.shape

(353, 10)

In [78]:
mbdg = MiniBatchGD(batch_size = int(X_train.shape[0] / 50), learning_rate = 0.05, epochs = 100)

In [79]:
int(X_train.shape[0] / 50)

7

In [80]:
mbdg.fit(X_train, y_train)

[   4.45406507 -205.09219668  534.00824222  329.28534668  -73.25828206
  -94.15859192 -168.25004216   69.90504466  546.09305041   53.01588035]
151.00426741646373


In [81]:
y_pred = mbdg.predict(X_test)

r2_score(y_test, y_pred)

0.44352192170683213

# Using Sklearn

In [82]:
from sklearn.linear_model import SGDRegressor

In [84]:
sgd = SGDRegressor(learning_rate = 'constant', eta0 = 0.2)

In [85]:
batch_size = 35

for i in range(100):
    idx = random.sample(range(X_train.shape[0]), batch_size)
    sgd.partial_fit(X_train[idx], y_train[idx])

In [86]:
sgd.coef_

array([   5.21314003, -168.50868408,  453.02804687,  281.93309784,
        -29.23163301,  -93.28376622, -198.48264141,  132.89757219,
        393.1067924 ,  122.78840099])

In [87]:
sgd.intercept_

array([149.64423378])

In [90]:
y_pred = sgd.predict(X_test)

r2_score(y_test, y_pred)

0.46169841445499205